config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'application#index'

  get '/in-memory-cache', to: 'in_memory_cache#index'

  get '/browser-cache-indefinite', to: 'browser_cache#indefinite'
  get '/browser-cache-short-ttl', to: 'browser_cache#short_ttl'
  get '/browser-cache-etag-based-on-content', to: 'browser_cache#etag_based_on_content'
  get '/browser_cache_indefinite_with_tracker', to: 'browser_cache#indefinite_with_tracker'
  get '/pixel_tracker', to: 'browser_cache#pixel_tracker'

  get '/view-cache', to: 'view_cache#index'

  get '/image-optimizer', to: 'image_optimizer#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
        render template: 'render_content', locals: { description: '', content: '' }
    end
end

app/controllers/browser_cache_controller.rb
# https://devcenter.heroku.com/articles/http-caching-ruby-rails
class BrowserCacheController < ApplicationController
    include BenchmarkHelper

    before_action :before_action_fresh_when, except: [:etag_based_on_content]

    def short_ttl
        expires_in ttl, public: true
        work description: "[#{SecureRandom.uuid}] The content of this page is set to expire every #{ttl} seconds, but may not refresh because the etag is the same. Important: know this behaviour"
    end

    def indefinite_with_tracker
        tracker = <<-JS
            <div id="tracked-view">
                <iframe src="#{pixel_tracker_path}"></iframe>
            </div>
        JS
        work description: "[#{SecureRandom.uuid}] The content of this page does not refresh, but homepage views are tracked. Current views: #{cookies[:views] || 'N/A'}<br /><br />#{tracker}"
    end

    def indefinite
        work description: "[#{SecureRandom.uuid}] The content of this page does not refresh"
    end

    def etag_based_on_content
        etag_based_on_content = 'etag_based_on_content'
        if (request.headers['If-None-Match'].nil?)
            Rails.cache.delete(etag_based_on_content)
        end

        etag = Rails.cache.fetch(etag_based_on_content, expires_in: ttl) { 
            SecureRandom.uuid 
        }

        if stale? etag: etag
            work description: "[#{etag}] This page is cached but will refresh every #{ttl} seconds because the ETag will change. Note that the etag is computed everytime, so there's server work"
        end
    end

    def pixel_tracker
        increase_views
        render plain: "[#{SecureRandom.uuid}] View tracked - OK - #{cookies[:views]}"
    end

    private

    def increase_views
        cookies[:views] = (cookies[:views].to_i || 0) + 1
    end

    def before_action_fresh_when
        fresh_when etag: request.fullpath unless request.path.include? 'pixel_tracker'
    end

    def work(description: '', content: '')
        reset_cache
        bms = benchmark do |x|
            x.report("Cached value first pass:") { cache }
            x.report("Cached value:") { cache }
            x.report("No cache:") { no_cache }
        end

        render template: 'render_content', locals: { description: description.html_safe, content: content.html_safe << bms.join('<br />').html_safe }
    end
end

app/controllers/image_optimizer_controller.rb
class ImageOptimizerController < ApplicationController
    def index
    end

    private
end

app/controllers/in_memory_cache_controller.rb
class InMemoryCacheController < ApplicationController
    include BenchmarkHelper
    
    def index
        reset_cache
        bms = benchmark do |x|
            x.report("Cached value first pass:") { cache }
            x.report("Cached value:") { cache }
            x.report("No cache:") { no_cache }
        end

        render template: 'render_content', locals: { description: "[#{SecureRandom.uuid}] In-Memory caching example", content: bms.join('<br />').html_safe }
    end

    private
end

app/controllers/view_cache_controller.rb
# https://devcenter.heroku.com/articles/http-caching-ruby-rails
class ViewCacheController < ApplicationController
    include BenchmarkHelper

    def index
        bm = Object.new
        bm.extend(BenchmarkHelper)
        render locals: { helper: bm, ttl: ttl }
    end
    
    private
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/image_optimizer/index.html.erb
<!-- Free, no attribution required: https://pixabay.com/photos/mountain-landscape-mountains-2031539/ -->
<div id="image">
    <h2>Example of optimized asset</h2>
    This example doesn't work well in non-production mode. <br /><br />

    <span class="images">
        <strong>Not optimized:</strong>
        <a href="<%= image_path('image.jpg') %>" target="image"><%= image_tag('image.jpg') %></a>
    </span>

    <span class="images">
        <strong>Optimized:</strong>
        <a href="<%= image_path('image.jpg', { optimized: 'true' }) %>" optimized="true" target="image"><%= image_tag('image.jpg', { optimized: 'true' }) %></a>
    </span>

    <span class="images">
        <strong>WebP Optimized:</strong>
        <a href="<%= image_path('image.jpg', { optimized: 'true', webp: 'true' }) %>" optimized="true" target="image"><%= image_tag('image.jpg', { optimized: 'true', webp: 'true' }) %></a>
    </span>
</div>

<div id="status">Waiting to optimize</div>

<script>
    $(function() {
        $('[webp=true').each(function() {
            let val = ''
            if ($(this).attr('src') !== undefined) {
                val = this.src.replace('jpg', 'jpg.webp')
                console.log("Updating to: " + val);
                $(this).attr('src', val);
            } else if ($(this).attr('href') !== undefined) {
                val = this.href.replace('jpg', 'jpg.webp')
                console.log("Updating to: " + val);
                $(this).attr('href', val);
            }
        });
    });
    
    setTimeout(() => {
        $('[optimized=true').each(function() {
            let val = ''
            if ($(this).attr('src') !== undefined) {
                val = this.src.replace('small', 'original')
                console.log("Updating to: " + val);
                $(this).attr('src', val);
            } else if ($(this).attr('href') !== undefined) {
                val = this.href.replace('small', 'original')
                console.log("Updating to: " + val);
                $(this).attr('href', val);
            }
        });
        $('#status').html('done');
    }, 4000);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PocCachingLayersRor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="<%= in_memory_cache_path %>">In-Memory Cache</a></li>
        <li><a href="<%= browser_cache_indefinite_path %>">Browser Cache Indefinite</a></li>
        <li><a href="<%= browser_cache_indefinite_with_tracker_path %>">Browser Cache Indefinite With Tracker</a></li>
        <li><a href="<%= browser_cache_short_ttl_path %>">Browser Cache Short TTL</a></li>
        <li><a href="<%= browser_cache_etag_based_on_content_path %>">Browser Cache based on ETAG</a></li>
        <li><a href="<%= view_cache_path %>">View Cache</a></li>
        <li><a href="<%= image_optimizer_path %>">Image Optimizer</a></li>
    </ul>
    <br />
    <div id="body">
    <%= yield %>
    </div>
  </body>
</html>

app/views/view_cache/_cached_content.html.erb
TTL for this view is <%= ttl %> seconds<br />
<%
    bms = helper.benchmark do |x|
        x.report("Total execution time]:") do
            cache 'view_cache_index', expires_in: ttl do
            %>
                Executing work [<%= SecureRandom.uuid %>] for <%= helper.no_cache.total %> seconds <br />
            <%
            end
        end
    end
%>
<br />
<%= bms.last.html_safe %>

app/views/view_cache/index.html.erb
<strong>Render #1</strong>
<%= render partial: 'cached_content', locals: { helper: helper, ttl: ttl } %>
<br />
<br />
<strong>Render #2</strong>
<%= render partial: 'cached_content', locals: { helper: helper, ttl: ttl } %>